"""tablas iniciales

Revision ID: 191a3f1281e2
Revises: 
Create Date: 2026-07-05 00:49:26.815500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '191a3f1281e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_libro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('facultades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('plantillas_notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('cuerpo_mensaje', sa.Text(), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bloqueado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fecha_bloqueo', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.CheckConstraint("rol IN ('bibliotecario', 'estudiante', 'gerente')", name='chk_usuarios_rol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=False),
    sa.Column('operacion', sa.String(length=10), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datos_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datos_nuevos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('modulo', sa.String(length=30), nullable=True),
    sa.CheckConstraint("operacion IN ('INSERT', 'UPDATE', 'DELETE')", name='chk_auditoria_operacion'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('nacionalidad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nacionalidad_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('facultad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facultad_id'], ['facultades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracion_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('modificado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['modificado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('editoriales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('dispositivo', sa.String(length=200), nullable=True),
    sa.Column('resultado', sa.String(length=10), nullable=False),
    sa.Column('motivo_cierre', sa.String(length=20), nullable=True),
    sa.CheckConstraint("motivo_cierre IN ('logout', 'expiracion', 'forzado')", name='chk_sesiones_motivo_cierre'),
    sa.CheckConstraint("resultado IN ('exitoso', 'fallido')", name='chk_sesiones_resultado'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('carrera_id', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=1), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.String(length=15), server_default='activo', nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("cedula ~ '^[0-9]{10}$'", name='chk_estudiantes_cedula'),
    sa.CheckConstraint("correo ~ '^[^@]+@[^@]+\\.[^@]+$'", name='chk_estudiantes_correo'),
    sa.CheckConstraint("estado IN ('activo', 'suspendido')", name='chk_estudiantes_estado'),
    sa.CheckConstraint("genero IN ('M', 'F', 'O')", name='chk_estudiantes_genero'),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('libros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=13), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('subtitulo', sa.String(length=255), nullable=True),
    sa.Column('editorial_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('anio_publicacion', sa.Integer(), nullable=True),
    sa.Column('edicion', sa.String(length=20), nullable=True),
    sa.Column('num_paginas', sa.Integer(), nullable=True),
    sa.Column('idioma', sa.String(length=30), server_default='Español', nullable=False),
    sa.Column('stock_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stock_disponible', sa.Integer(), server_default='0', nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('LENGTH(isbn) = 13', name='chk_libros_isbn_longitud'),
    sa.CheckConstraint('anio_publicacion BETWEEN 1800 AND EXTRACT(YEAR FROM NOW())', name='chk_libros_anio_publicacion'),
    sa.CheckConstraint('num_paginas > 0', name='chk_libros_num_paginas'),
    sa.CheckConstraint('stock_disponible <= stock_total', name='chk_libros_stock_coherente'),
    sa.CheckConstraint('stock_disponible >= 0', name='chk_libros_stock_disponible_positivo'),
    sa.CheckConstraint('stock_total >= 0', name='chk_libros_stock_total_positivo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_libro.id'], ),
    sa.ForeignKeyConstraint(['editorial_id'], ['editoriales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('ejemplares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('codigo_ejemplar', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=15), server_default='disponible', nullable=False),
    sa.Column('fecha_adquisicion', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.CheckConstraint("estado IN ('disponible', 'prestado', 'dañado', 'baja')", name='chk_ejemplares_estado'),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_ejemplar')
    )
    op.create_table('libro_autor',
    sa.Column('libro_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.ForeignKeyConstraint(['libro_id'], ['libros.id'], ),
    sa.PrimaryKeyConstraint('libro_id', 'autor_id')
    )
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_prestamo', sa.String(length=20), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('ejemplar_id', sa.Integer(), nullable=False),
    sa.Column('bibliotecario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_prestamo', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=10), server_default='activo', nullable=False),
    sa.Column('renovaciones', sa.Integer(), server_default='0', nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.CheckConstraint("estado IN ('activo', 'devuelto', 'vencido')", name='chk_prestamos_estado'),
    sa.CheckConstraint('fecha_limite > fecha_prestamo::DATE', name='chk_prestamos_fecha_limite'),
    sa.CheckConstraint('renovaciones >= 0', name='chk_prestamos_renovaciones'),
    sa.ForeignKeyConstraint(['bibliotecario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ejemplar_id'], ['ejemplares.id'], ),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_prestamo')
    )
    op.create_table('devoluciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prestamo_id', sa.Integer(), nullable=False),
    sa.Column('bibliotecario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_devolucion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado_ejemplar', sa.String(length=15), nullable=False),
    sa.Column('dias_retraso', sa.Integer(), server_default='0', nullable=False),
    sa.Column('multa_generada', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('multa_pagada', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fecha_pago_multa', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.CheckConstraint("estado_ejemplar IN ('bueno', 'dañado', 'perdido')", name='chk_devoluciones_estado_ejemplar'),
    sa.CheckConstraint('dias_retraso >= 0', name='chk_devoluciones_dias_retraso'),
    sa.CheckConstraint('multa_generada >= 0', name='chk_devoluciones_multa_positiva'),
    sa.ForeignKeyConstraint(['bibliotecario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prestamo_id')
    )
    op.create_table('historial_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ejemplar_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=15), nullable=False),
    sa.Column('estado_anterior', sa.String(length=15), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=15), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('prestamo_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.CheckConstraint("tipo_movimiento IN ('adquisicion', 'prestamo', 'devolucion', 'baja', 'danio')", name='chk_historial_inventario_tipo'),
    sa.ForeignKeyConstraint(['ejemplar_id'], ['ejemplares.id'], ),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('prestamo_id', sa.Integer(), nullable=True),
    sa.Column('plantilla_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(), nullable=False),
    sa.Column('fecha_enviada', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=10), server_default='pendiente', nullable=False),
    sa.Column('canal', sa.String(length=10), nullable=False),
    sa.Column('leida', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(), nullable=True),
    sa.CheckConstraint("canal IN ('sistema', 'correo')", name='chk_notificaciones_canal'),
    sa.CheckConstraint("estado IN ('pendiente', 'enviada', 'fallida')", name='chk_notificaciones_estado'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ),
    sa.ForeignKeyConstraint(['plantilla_id'], ['plantillas_notificacion.id'], ),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renovaciones_prestamo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prestamo_id', sa.Integer(), nullable=False),
    sa.Column('bibliotecario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_renovacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_limite_anterior', sa.Date(), nullable=False),
    sa.Column('fecha_limite_nueva', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bibliotecario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['prestamo_id'], ['prestamos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('danios_perdidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devolucion_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('costo_estimado', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('reportado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resuelto', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("tipo IN ('danio', 'perdida')", name='chk_danios_perdidas_tipo'),
    sa.CheckConstraint('costo_estimado >= 0', name='chk_danios_perdidas_costo_positivo'),
    sa.ForeignKeyConstraint(['devolucion_id'], ['devoluciones.id'], ),
    sa.ForeignKeyConstraint(['reportado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('danios_perdidas')
    op.drop_table('renovaciones_prestamo')
    op.drop_table('notificaciones')
    op.drop_table('historial_inventario')
    op.drop_table('devoluciones')
    op.drop_table('prestamos')
    op.drop_table('libro_autor')
    op.drop_table('ejemplares')
    op.drop_table('libros')
    op.drop_table('estudiantes')
    op.drop_table('sesiones')
    op.drop_table('editoriales')
    op.drop_table('configuracion_sistema')
    op.drop_table('carreras')
    op.drop_table('autores')
    op.drop_table('auditoria')
    op.drop_table('usuarios')
    op.drop_table('plantillas_notificacion')
    op.drop_table('paises')
    op.drop_table('facultades')
    op.drop_table('categorias_libro')
    # ### end Alembic commands ###
